# -*- coding: utf-8 -*-
"""notebook2187957611.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SG0OStJRDmFKLN0bqkhPstxxGU5RdVg8

# **AMAZON SALES DATA ANALYSIS (EDA)**

This notebook explores Amazon sales data to uncover patterns, trends, and insights about pricing, discounts, customer behavior, and category performance.  
This dataset is having the data of 1K+ Amazon Product's as per their details listed on the official website of Amazon

# **Objectives**

* Clean and preprocess raw sales data.
* Handle missing values, duplicates, and inconsistent entries.
* Perform univariate, bivariate, and multivariate analysis.
* Identify key insights from the analysis.
* Create meaningful visualizations for better storytelling.

# **Dataset Features**:

- product_id: Product ID
- product_name: Name of the Product
- category: Category of the Product
- discounted_price: Discounted Price of the Product
- actual_price: Actual Price of the Product
- discount_percentage: Percentage of Discount
- rating: Rating of the Product
- rating_count: Number of people who voted
- about_product: Product description
- user_id: ID of the reviewer
- user_name: Name of the reviewer
- review_id: Review ID
- review_title: Short review
- review_content: Long review
- img_link: Product image link
- product_link: Official product link

# **EDA Workflow**

This analysis is structured into the following steps:

1. **Data Understanding**
   - Load the dataset
   - Explore features, info, and basic statistics  
   - Summarize dataset statistics

2. **Data Cleaning & Preparation**
   - Data type conversions
   - Duplicate removal
   - Handle missing values
   - Outliners detection
   - Describing data

3. **Univariate Analysis**
   - distribution of ratings and discount percentage
   - most frequent product categories
   - WordCloud for keywords in product name

4. **Bivariate Analysis**
   - Do higher discounts(discount_percentage) lead to higher sales (rating_count)?
   - Is there a correlation between actual price and discounted price?
   - How do ratings vary by popularity(rating_count)?

5. **Multivariate Analysis**
   - Which features are most strongly correlated?
   - Which categories show the best balance of high ratings, high discounts, and popularity?

6. **Review Analysis**
   - Explore customer reviews for common words and sentiments

7. **Key Insights & Observations**
   - Summarize findings from all the analysis

8. **Conclusion & Outcomes**

# **Importing Libraries**
"""

# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
import scipy.stats as stats

"""# **Data Understanding**

We begin by loading the dataset and checking its dimensions and first and last few rows to understand the structure.

### **Load the dataset**
"""

# Load the CSV file into a DataFrame
data = pd.read_csv("sample_data/amazon.csv")

# Set the option to show maximum columns
pd.set_option('display.max_columns', None)

"""### **Explore features, data types, and basic statistics**"""

# Let's have a look on top 5 rows (default) of the data
data.head()

# Let's have a look on last 5 rows (default) of the data
data.tail()

# Column Names
data.columns

# Columns and their data types using detailed info function
data.info()

"""### **Summarize dataset statistics**"""

data.describe()

"""# **Data Cleaning & Preparation**

### **Data type conversions**
"""

# Changing the Data Type of 'discounted_price' from object to float and removing symbols
data['discounted_price'] = data['discounted_price'].str.replace('₹', '')
data['discounted_price'] = data['discounted_price'].str.replace(',', '')
data['discounted_price'] = data['discounted_price'].astype(float)

# Changing the Data Type of 'actutal_price' from object to float and removing symbols
data['actual_price'] = data['actual_price'].str.replace('₹', '')
data['actual_price'] = data['actual_price'].str.replace(',', '')
data['actual_price'] = data['actual_price'].astype(float)

# Changing Data Type and values in 'discount_percentage'
data['discount_percentage'] = data['discount_percentage'].str.replace('%', '')
data['discount_percentage'] = data['discount_percentage'].astype(float)

# Finding unusual 'rating'
data['rating'].value_counts()

# Check the strange row
data.query('rating == "|"')

# I got this product rating on Amazon by searching the provided product_id on their official website (amazon.in)
# The rating is 3.9. So, I am going to give the item rating a 3.9 as well.
data['rating']  = data['rating'].str.replace('|', '3.9')

# Changing rating column Data Type
data['rating']  = data['rating'].astype(float)

# Changing 'rating_count' Column Data Type
data['rating_count'] = data['rating_count'].str.replace(',', '').astype(float)

data.info()

"""### **Duplicate removal**"""

# FInd Duplicates
data.duplicated().any()

data.columns

data.duplicated(subset = ['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link']).any()

"""##### Hence No duplicates found

### **Handle missing values**
"""

# Missing Values
data.isnull().sum().sort_values(ascending = False)

# Finding missing values percentage in the data
round(data.isnull().sum() / len(data) * 100 , 2).sort_values(ascending = False)

# Find total number of missing values
data.isnull().sum().sum()

# Plotting missing values by percentage
plt.figure(figsize = (14, 9))
missing_percentage = data.isnull().sum() / len(data) * 100
missing_percentage.plot(kind='bar')
plt.xlabel('Columns')
plt.ylabel('Missing Values Percentage')
plt.title('Missing Values Percentage in Columns')
plt.show()

# Rows where there are null values in the column
data[data['rating_count'].isnull()]

# Impute Missing Values
data['rating_count'] = data['rating_count'].fillna(data['rating_count'].median())

data.isnull().sum().sort_values(ascending = False)

"""##### We have cleaned the dataset from null values

### **Outliners Detection**
"""

data[data['discounted_price'] > data['actual_price']]

data[data['rating'] > 5]

data[data['discount_percentage'] > 100]

sns.boxplot(data['discount_percentage'])

"""From the above analysis we can conclude that there are no outliners in the data.

### **Describing Data**
"""

# Describe summarize and describe the main characteristics of a dataset
data.describe()

"""# **Univariate Analysis**

First, we analyze individual features to understand their distributions.

### **Distribution of ratings and discount_percentage**
"""

# Ratings distribution
plt.figure(figsize = (13, 5))
sns.histplot(data["rating"], bins=20, kde=True)
plt.title("Distribution of Ratings")
plt.show()

"""mostly ratings are between 4.0 and 4.5"""

# Discount Percentage distribution
plt.figure(figsize = (13, 5))
sns.kdeplot(data['discount_percentage'], shade=True)
plt.title("Discount Percentage Distribution")
plt.show()

"""Discount on most of the products is between 50 and 60. we can say amazon is giving good discount on most of its products.

### **Most Frequent product categories**
"""

# Most Frequent product categories
category_counts = data['category'].value_counts()
category_counts.head()

"""### **WordCloud for keywords in product name**"""

# Extracts cleaned keywords from a product name, keeping alphanumeric tokens
import re
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# Define stopwords (you can expand this list manually if not using nltk)
stop_words = set(stopwords.words('english'))

def extract_keywords(product_name):
    if isinstance(product_name, str):
        tokens = re.findall(r"[a-zA-Z0-9]+", product_name.lower())                        # Use regex to split on non-alphanumeric characters
        keywords = [word for word in tokens if word not in stop_words and len(word) > 1]  #  Remove stopwords & single-letter tokens
    else:
        keywords = []
    return keywords

# Apply function
data["keywords"] = data["product_name"].apply(extract_keywords)

# Flatten list of keywords
all_keywords = [kw for kws in data["keywords"] for kw in kws]

# Count occurrences
keyword_counts = pd.Series(all_keywords).value_counts()

# Top 10
print(keyword_counts.head(10))

from wordcloud import WordCloud
# Combine text data into a single string
text = ' '.join([' '.join(kws) for kws in data['keywords']])

# Generate word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white', max_words = 15).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud)
plt.title('Frequent Words in Products')
plt.axis('off')
plt.show()

"""* Black color products are mostly ordered products and then white color products.
* USB, charging (especially fast charging), and cables are prominent product features.
* Cables and smart devices are likely well-represented in the dataset.
* Product names tend to be concise and use common words, potentially benefiting from refined keyword extraction techniques.

### **most popular product name?**
"""

product_counts = data['product_name'].value_counts()
product_counts.head(10).sort_values(ascending = False)

"""Fire-Boltt Ninja Call Pro Plus Smart Watch is the most popular product, followed by Fire-Boltt Phoenix Smart Watch.

Smart Watches and Charging Cables are the most popular product categories.

Fast charging, durability, and functionality are key features.

# **Bivariate Analysis**

### **Do higher discounts(discount_percentage) lead to higher sales (rating_count)?**
"""

# Calculate Correlation Coefficient between 'Discount_percentage' and 'rating_count'
round(data['discount_percentage'].corr(data['rating_count'], method = 'spearman'), 2)

plt.figure(figsize = (13, 5))
sns.scatterplot(x="discount_percentage", y="rating_count", data=data, alpha=0.5)
plt.title("Discount % vs Popularity (Rating Count)")
plt.show()

"""Discount Percentage and higher sales(rating_count) have a negative correlation. This means As one variable goes up, the other tends to go down slightly, but the relationship is very weak and might be just random noise. we can say there is no relationship.

### **Is there a correlation between actual price and discounted price?**
"""

# Calculate Correlation Coefficient between 'actutal_price' and 'discounted_price'
round(data['discounted_price'].corr(data['actual_price'], method = 'spearman'), 2)

# Actual vs Discounted Price
plt.figure(figsize = (13, 5))
sns.scatterplot(x="actual_price", y="discounted_price", data=data, alpha=0.5)
plt.xticks(range(0, 90000, 10000))
plt.yticks(range(0, 60000, 10000))
plt.xlim(0, 80000)
plt.ylim(0, 50000)
plt.title("Actual Price vs Discounted Price")
plt.show()

"""Discounted price and actutal price have a 0.93 Positive correlation. This means As one variable goes up, the other goes up or vice-versa, the relationship is too strong as it is near to 1. we can say there is relationship between discounted price and actutal price.
Also most products are concentrated in the lower price brackets, indicating affordability is a key factor in the dataset.
"""

discounted_price_median = data['discounted_price'].median()
print("Discounted Price Median is: ", discounted_price_median)

actual_price_median = data['actual_price'].median()
print("Actual Price Median is: ", actual_price_median)

# Calculate and analyze discount percentages
plt.figure(figsize=(13,5))
plt.hist(data['discount_percentage'], bins=20, color='green', alpha=0.7)
plt.xlabel("Discount Percentage (%)")
plt.ylabel("Number of Products")
plt.title("Distribution of Discount Percentage")
plt.show()

# skewness of disocunted_percentage
data['discount_percentage'].skew()

"""The output shows that discounted prices are generally lower than actual prices, with a median discounted price of 799 and a median actual price of 1650.

The discount percentage distribution is skewed slightly to the left, means mostly products have higher discounts.

### **How do ratings vary by popularity(rating_count)?**
"""

# Calculate Correlation Coefficient between 'rating' and 'rating_count'
round(data['rating'].corr(data['rating_count'], method = 'spearman'), 2)

# Ratings vs rating count (Popularity)
plt.figure(figsize = (13, 5))
sns.scatterplot(x="rating", y="rating_count", data=data, alpha=0.5)
plt.title("Ratings vs Popularity")
plt.show()

"""- rating and rating_count have a 0.18 Positive correlation. This means As one variable goes up, the other goes up or vice-versa, the relationship is not very strong as it is far away from 1. but still we can say that there is relationship between discounted price and actutal price.

 - Most products have ratings clustered between 3.5 and 5 stars, with varying popularity.

 - The spread suggests that high ratings alone do not guarantee popularity—some well-rated products have low engagement, while others with similar ratings attract thousands of reviews.

 - Popular products tend to maintain ratings above 4.0, suggesting that strong quality helps sustain customer interest.

### **Actual Price vs Rating**
This scatter plot shows the relationship between a product’s actual price (x-axis) and its customer rating (y-axis).
Each point represents a product.
"""

# Scatter Plot
# Plotting actual_price vs rating
plt.figure(figsize=(13, 5))
plt.scatter(data['actual_price'], data['rating'])
plt.xlabel('Actual Price')
plt.ylabel('Rating')
plt.title('Actual Price vs Rating')
plt.show()

"""Most products are concentrated in the lower price range between 0 to 25000, with ratings between 3.5 to 5.

Higher-priced products are fewer, but they generally maintain similar rating patterns.

This suggests that price does not have a strong direct correlation with product rating—customers rate products more on quality and experience rather than just price.

# **Multivariate Analysis**

Study interactions among multiple variables using correlation heatmaps and grouped analysis.

### **Which features are most strongly correlated?**
"""

# Calculating pearson Correlation Coefficients (for linear relationships)
pearson_correlation_matrix = round(data.corr(numeric_only=True),2)
print(pearson_correlation_matrix)

# Create a Heatmap to visualize the correlations
plt.figure(figsize=(13, 5))
sns.heatmap(pearson_correlation_matrix, annot=True, cmap="coolwarm")
plt.title("pearson correlation matrix")
plt.show()

# Calculating Spearman Correlation Coefficients (for non-linear relationships)
spearman_correlation_matrix = round(data.corr(method = "spearman", numeric_only=True),2)
print(spearman_correlation_matrix)

# Create a Heatmap to visualize the correlations
plt.figure(figsize=(13, 5))
sns.heatmap(spearman_correlation_matrix, annot=True, cmap="coolwarm")
plt.title("spearman correlation matrix")
plt.show()

"""#### **Correlation of Whole Data**

**When we want to run correlation analysis, we need numeric data only. Since most of our original dataset has text and categorical variables.
If we want to analysis whole data correlations we can make a copy of original dataset (after cleaning) and then we can apply LabelEncoder on non-numeric columns, so that original Data won't be affected for other analysis.
Below cell conatins all codes for pearson and spearman correlation, to uncomment select everthing in cell and then press Ctrl + / (Windows/Linux) or Command + / (macOS) and run**
"""

# # Creating a deep copy of Original Dataset
# data_copy = data.copy()

# from sklearn.preprocessing import LabelEncoder
# # label encode categorical variables
# # LabelEncoder converts unique values in a column into integers

# data_copy['product_id'] = LabelEncoder().fit_transform(data_copy['product_id'])
# data_copy['category'] = LabelEncoder().fit_transform(data_copy['category'])
# data_copy['review_id'] = LabelEncoder().fit_transform(data_copy['review_id'])
# data_copy['review_content'] = LabelEncoder().fit_transform(data_copy['review_content'])
# data_copy['product_name'] = LabelEncoder().fit_transform(data_copy['product_name'])
# data_copy['user_name'] = LabelEncoder().fit_transform(data_copy['user_name'])
# data_copy['about_product'] = LabelEncoder().fit_transform(data_copy['about_product'])
# data_copy['user_id'] = LabelEncoder().fit_transform(data_copy['user_id'])
# data_copy['review_title'] = LabelEncoder().fit_transform(data_copy['review_title'])
# data_copy['img_link'] = LabelEncoder().fit_transform(data_copy['img_link'])
# data_copy['product_link'] = LabelEncoder().fit_transform(data_copy['product_link'])

# # Calculating Pearson Correlation Coefficients (Default in Pandas)
# correlation_matrix = round(data_copy.corr(),2)
# print(correlation_matrix)

# # Create a Heatmap to visualize the correlations
# plt.figure(figsize=(13, 5))
# sns.heatmap(correlation_matrix, annot = True, cmap = "coolwarm")
# plt.title("Correlation Matrix (Pearson)")
# plt.show()

# # Calculating Spearman Correlation Coefficients (for non-linear relationships)
# spearman_correlation_matrix = round(data_copy.corr(method = "spearman"),2)
# print(spearman_correlation_matrix)

# # Create a Heatmap to visualize the correlations
# plt.figure(figsize=(13, 5))
# sns.heatmap(spearman_correlation_matrix, annot = True, cmap = "coolwarm")
# plt.title("Correlation Matrix (Spearman)")
# plt.show()

"""### **Which categories show the best balance of high ratings, high discounts, and popularity?**"""

data.groupby("category")[["discount_percentage","rating","rating_count"]].mean().sort_values("rating_count", ascending=False).reset_index().head(10)

"""# **Review Analysis**

### **Explore customer reviews for common words and sentiments**
"""

# Extracts cleaned keywords from a review_content, keeping alphanumeric tokens
import re
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# Define stopwords (you can expand this list manually if not using nltk)
stop_words = set(stopwords.words('english'))

def extract_keywords(review_content):
    if isinstance(review_content, str):
        tokens = re.findall(r"[a-zA-Z0-9]+", review_content.lower())                        # Use regex to split on non-alphanumeric characters
        keywords = [word for word in tokens if word not in stop_words and len(word) > 1]  #  Remove stopwords & single-letter tokens
    else:
        keywords = []
    return keywords

# Apply function
data["keywords"] = data["review_content"].apply(extract_keywords)

# Flatten list of keywords
all_keywords = [kw for kws in data["keywords"] for kw in kws]

# Count occurrences
keyword_counts = pd.Series(all_keywords).value_counts()

# Plotting Top 15 Most Frequent Words in Reviews
plt.figure(figsize=(13, 5))
bars = plt.bar(keyword_counts.index[:15], keyword_counts.values[:15])
plt.xlabel("Keyword")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.title("Top 15 Most Frequent Words in Reviews")
# Adding frequency labels on top of each bar
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height,   # Position
             str(height),                               # Label text
             ha='center', va='bottom', fontsize=10)     # Alignment
plt.show()

"""This bar chart displays the 15 most common keywords extracted from customer reviews after cleaning and removing stopwords. The x-axis shows keywords, and the y-axis shows how many times each keyword appears across all reviews."""

from wordcloud import WordCloud
# Combine text data into a single string
text = ' '.join([' '.join(kws) for kws in data['keywords']])

# Generate word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white', max_words = 15).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud)
plt.title('Frequent Words in Reviews')
plt.axis('off')
plt.show()

"""# **Products Recommendation**"""

data["product_id"].duplicated().sum()

data["product_name"].duplicated().sum()

data = data.drop_duplicates(subset="product_id").reset_index(drop=True)

data = data.drop_duplicates(subset="product_name").reset_index(drop=True)

def clean_price(x):
    x = str(x).replace("₹","").replace(",","").strip()
    return float(x) if x.replace(".","",1).isdigit() else None

data["price"] = data["discounted_price"].apply(clean_price)

data["full_text"] = (data["product_name"].astype(str) + " " +
                   data["about_product"].astype(str) + " " +
                   data["category"].astype(str)).str.lower()

data["main_category"] = data["category"].apply(lambda x: str(x).split("|")[0].lower())

def extract_num(text, pattern):
    match = re.search(pattern, text, re.IGNORECASE)
    return float(match.group(1)) if match else None

import re

def extract_features(row):
    text = row["full_text"]

    features = {}

    # ---------------------------------------
    # 1️⃣ BRAND
    # ---------------------------------------
    features["brand"] = row["product_name"].split()[0].lower()

    # ---------------------------------------
    # 2️⃣ LENGTH FEATURES (m, ft, cm)
    # ---------------------------------------
    features["length_m"]  = extract_num(text, r"(\d+(\.\d+)?)\s*m")
    features["length_cm"] = extract_num(text, r"(\d+)\s*cm")
    features["length_ft"] = extract_num(text, r"(\d+)\s*ft")

    # unify
    if features["length_cm"]: features["length_m"] = features["length_cm"] / 100
    if features["length_ft"]: features["length_m"] = features["length_ft"] * 0.3048

    # ---------------------------------------
    # 3️⃣ WATT / POWER
    # ---------------------------------------
    features["watts"] = extract_num(text, r"(\d+)\s*w")

    # ---------------------------------------
    # 4️⃣ CONNECTOR TYPES
    # ---------------------------------------
    features["typec"]      = int(("type-c" in text) or ("type c" in text) or ("usb-c" in text))
    features["micro_usb"]  = int("micro usb" in text)
    features["lightning"]  = int("lightning" in text)
    features["usb_a"]      = int(("usb a" in text) or ("usb-a" in text))

    # ---------------------------------------
    # 5️⃣ FAST CHARGING FEATURES
    # ---------------------------------------
    fast_keywords = [
        "fast charging", "fast charge", "quick charge",
        "qc 3.0", "qc3.0", "power delivery", "pd", "rapid charge"
    ]
    features["fast_charge"] = int(any(kw in text for kw in fast_keywords))

    # ---------------------------------------
    # 6️⃣ MATERIAL
    # ---------------------------------------
    features["braided"]      = int("braided" in text)
    features["nylon"]        = int("nylon" in text)
    features["metal"]        = int("metal" in text or "aluminum" in text)
    features["tangle_free"]  = int("tangle" in text)

    # ---------------------------------------
    # 7️⃣ COLOR DETECTION
    # ---------------------------------------
    colors = ["black","white","red","blue","green","yellow",
              "silver","gold","grey","pink","purple"]
    for c in colors:
        features[f"color_{c}"] = int(c in text)

    # ---------------------------------------
    # 8️⃣ PACK / QUANTITY
    # ---------------------------------------
    features["pack_count"] = extract_num(text, r"pack of (\d+)")

    # ---------------------------------------
    # 9️⃣ DEVICE COMPATIBILITY
    # ---------------------------------------
    device_keywords = ["iphone","ipad","samsung","oneplus","vivo","oppo","android"]
    for d in device_keywords:
        features[f"supports_{d}"] = int(d in text)

    # ---------------------------------------
    # 🔟 DURABILITY SCORE
    # ---------------------------------------
    durability_words = ["durable","strong","reinforced","heat-resistant","heavy-duty","premium"]
    features["durability_score"] = sum(1 for w in durability_words if w in text)

    # ---------------------------------------
    # 1️⃣1️⃣ PRICE BUCKET
    # ---------------------------------------
    features["price_bucket"] = int(row["price"] // 500) if row["price"] else 0

    # ---------------------------------------
    # 1️⃣2️⃣ CATEGORY
    # ---------------------------------------
    features["category_match"] = row["main_category"]

    # ---------------------------------------
    # 1️⃣3️⃣ TEXT FOR TF-IDF
    # ---------------------------------------
    features["keywords"] = text

    return features

data["features"] = data.apply(extract_features, axis=1)

data.head(3)

numeric_keys = []
for f in data["features"]:
    for k, v in f.items():
        if isinstance(v, (int, float)):
            numeric_keys.append(k)

numeric_keys = list(set(numeric_keys))  # unique
numeric_keys

for key in numeric_keys:
    data[key] = data["features"].apply(lambda x: x.get(key, None))

data.head(3)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_numeric = data[numeric_keys].replace(0, np.nan).fillna(data[numeric_keys].mean())
numeric_scaled = scaler.fit_transform(df_numeric)

numeric_scaled

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(stop_words="english", max_features=8000)
text_matrix = tfidf.fit_transform(data["full_text"])
numeric_sim_matrix = cosine_similarity(numeric_scaled)
text_sim_matrix = cosine_similarity(text_matrix)

def get_similarity(df, idx1, idx2):
    num_sim  = numeric_sim_matrix[idx1, idx2]
    text_sim = text_sim_matrix[idx1, idx2]

    # category boost
    cat_sim = 1 if df.loc[idx1,"main_category"] == df.loc[idx2,"main_category"] else 0

    # price bucket similarity
    price_sim = 1 if df.loc[idx1,"price_bucket"] == df.loc[idx2,"price_bucket"] else 0

    # final score
    return (0.50 * num_sim) + (0.35 * text_sim) + (0.10 * cat_sim) + (0.05 * price_sim)

def recommend(df, product_id, top_n=5):
    if product_id not in df["product_id"].values:
        return None
    idx = df.index[df["product_id"] == product_id][0]

    scores = [(i, get_similarity(df, idx, i)) for i in range(len(df)) if i != idx]
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    top_idx = [i[0] for i in scores[:top_n]]

    return df.loc[top_idx, ["product_id","product_name","main_category","price"]]

def recommend_by_product_id(df, product_id, top_n=5):
    if product_id not in df["product_id"].values:
        print("❌ Product ID not found")
        return None

    idx = df.index[df["product_id"] == product_id][0]
    return recommend_by_iloc(df, idx, top_n)

def recommend_by_iloc(df, index, top_n=5):
    if index < 0 or index >= len(df):
        print("Invalid index")
        return None

    p = df.iloc[index]

    print("\n📌 SELECTED PRODUCT")
    print("----------------------------------------")
    print(f"Name       : {p['product_name']}")
    print(f"Category   : {p['main_category']}")
    print(f"Price      : {p['price']}")
    print(f"Product ID : {p['product_id']}")
    print("----------------------------------------")

    print("\n🎯 TOP RECOMMENDATIONS\n")

    recs = recommend(df, p["product_id"], top_n)
    #print(tabulate(recs, headers='keys', tablefmt='github'))

    return recs

def recommend_by_product_id(df, product_id, top_n=5):
    if product_id not in df["product_id"].values:
        print("❌ Product ID not found")
        return None

    idx = df.index[df["product_id"] == product_id][0]
    return recommend_by_iloc(df, idx, top_n)

recommend_by_iloc(data, 480, 10)

"""# **Key Insights & Observations**

*   List item
*   List item

**Summarize findings from all the above analysis**

**Price:**
* Most products are concentrated in the lower price range between 0 to 25000, indicating affordability is a key factor in the dataset.
*	Price does not have a strong direct correlation with product rating—customers rate products more on quality and experience rather than just price.

**Products:**
* Most products have ratings between 4 to 4.5.
*	Black color products are mostly ordered products and then white color products.
*	Smart Watches and Charging Cables are the most popular product categories. Fast charging, durability, and functionality are key features.
*	Fire-Boltt Ninja Call Pro Plus Smart Watch is the most popular product, followed by Fire-Boltt Phoenix Smart Watch.

**Discount Percentage:**
* Discount percentage on most of the products is between 50% and 60%. we can say mostly products have higher discounts.
* Discount Percentage and rating & Sales(rating_count) have a negative correlation. This means as one variable goes up, the other tends to go down slightly, but the relationship is very weak. This means customers rate products more on quality and experience rather than just price.

**Ratings & Review:**
* High ratings alone do not guarantee popularity(rating_count) —some well-rated products have low engagement, while others with similar ratings attract thousands of reviews.
* The most frequent terms represent what customers talk about the most (e.g., good, product quality, price, delivery, usability).

# **Conclusion**

- Dataset was cleaned and preprocessed successfully.
- Performed univariate, bivariate, and multivariate analysis.
- Generated actionable insights on pricing, discounts, ratings, and categories.
- Set foundation for predictive modeling (sales forecasting, recommendation).
 - By conducting exploratory data analysis (EDA) on this dataset, businesses can gain valuable insights that can help them make better decisions about their products, marketing, and operations.
"""